# Basic Jekyll configuration for GitHub Pages

# Site settings
title: Shopify MCP Mock Server
description: An open-source MCP server for Shopify, supporting mock.shop for safe development and testing.
baseurl: "/ShopifyMCPMockShop" # the subpath of your site
url: "https://ramakay.github.io" # the base hostname & protocol

# Theme
theme: jekyll-theme-cayman